#!/bin/sh

changed=0

set_opt() {
	local key=$1
	local val=$2

	if ! uci -q get "luci.$key" 2>/dev/null; then
		uci set "luci.$key=$val"
		changed=1
	fi
}

set_opt themes.Goflow /luci-static/goflow

if [ "$PKG_UPGRADE" != 1 ] && [ $changed = 1 ]; then
	set_opt main.mediaurlbase /luci-static/goflow
fi

set_opt themes.GoflowDark /luci-static/goflow-dark
set_opt themes.GoflowLight /luci-static/goflow-light

# Initialise Goflow UCI config if not present
if ! uci -q get goflow.global 2>/dev/null; then
	uci -q batch <<-CFG
		set goflow.global=global
		set goflow.global.mode=auto
		set goflow.global.font_size=14
		set goflow.global.rail_collapsed=0
		set goflow.global.status_bar=1
		set goflow.global.dashboard=1
		commit goflow
	CFG
fi

if [ $changed = 1 ]; then
	uci commit luci
fi

rm -f /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null

exit 0
